package pl.dkobylarz.signlearning.domain.quizprocess.exception

class QuizAlreadyCompletedException: RuntimeException("This quiz is already completed by user!")
